### ISSUE TITLE
Should the RPC pre-edit documents before they get to the IESG?

### ISSUE THREAD

**Issue by ekr** [rfcseries-wg/new-topics#30]
Michael Richardson writes:

Hi, at a side meeting, I think in PHL, there was a discussion about git
(hub,lab) involvement and also RPC involvement.

I think that we might have discussed editorial passes to documents before
they get to the IESG.   I think that having the IESG waste it's time on
editorial issues is a serious mis-allocation of time/resources.
It will take more than one cycle, because WGLC comments, review comments and
IESG DISCUSS comments could each reduce the english quality in the document
to zero.

**Comment by huitema** [comment]
If I remember the discussions correctly, wasting IESG time was not the only issue. We were also concerned with changes in a document after IESG approval. In theory, such changes are only editorial. In practice, we are never sure. If a document is poorly written, it may need many changes for "readability". If there are many changes, risks of changing some of the meaning are large. Having the bulk of the changes done before IESG approval would fix that.

**Comment by mnot** [comment]
I've had this discussion many times as well, and agree that it's worth discusing yet again (esp. now that we have the RSWG).

I'd suggest considering:
- Getting the RPC involved earlier in the process, but with a focus on improving communication, not editorial corrections. E.g., help with overall writing style, tuning the abstract and introduction, document structure/organisation, how requirements are stated, etc.
- Giving stronger guidelines to reviewers (including the IESG) about pointing out editorial nits. It may be well-intended, but it subjects authors to a gauntlet of repeated 'helpful' suggestions, forming a death by a thousand cuts. This is a real impediment to getting new people involved the process. If reviewers must make these suggestions, they should be in a friendier form (e.g., PRs).

**Comment by becarpenter** [comment]
IMHO the policy issue here is roughly this:

Would the RFC Series as a whole benefit if RPC resources were used to improve drafts before their approval (or rejection) by each stream? It's entirely up to each stream whether and when they use such a service.

**Comment by peteresnick** [comment]
While an interesting topic, the chairs view this as out of scope of the charter and therefore are closing this issue.
